# This file was generated by GoReleaser. DO NOT EDIT.
cask "drift" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "5474b1d14a2f390f0e1a769f75b2da26c9fa3beae12f6bfacb0d617576423ee0"
      url "https://github.com/Sknoww/drift/releases/download/v#{version}/drift_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1595e0d88052ae13cf26737aaf24e3097b7e1eb96442b2bc21b81f1cd6bd7414"
      url "https://github.com/Sknoww/drift/releases/download/v#{version}/drift_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b8d33e323e7d9898896f37f5ea1fb5bc0374ca61182fe4a554a1413f87859d14"
      url "https://github.com/Sknoww/drift/releases/download/v#{version}/drift_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "625941d52c156787f1ea2af3fa176bc519b11af9bef00f8d1e00a28a122954b6"
      url "https://github.com/Sknoww/drift/releases/download/v#{version}/drift_#{version}_linux_arm64.tar.gz"
    end
  end

  name "drift"
  desc "Ticket-based git TUI"
  homepage "https://github.com/Sknoww/drift"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "drift"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/drift"]
    end
  end

  # No zap stanza required

end
