# This file was generated by GoReleaser. DO NOT EDIT.
cask "drift" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "ab807f179cfe76002559db4c2c103fbf6073b4405b276720736a1936ac228d72"
      url "https://github.com/Sknoww/drift/releases/download/v#{version}/drift_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "28d57041f021ea05e7d3e72a6eee23cfd88932179a2f9cdc1dc59f252031076d"
      url "https://github.com/Sknoww/drift/releases/download/v#{version}/drift_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a0a46c8b36af0f6dc1692cfea3685522634095ddfbbfc698d4b6ed8b764ee796"
      url "https://github.com/Sknoww/drift/releases/download/v#{version}/drift_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8ef12da8169d40f0d8a42f25951365c39399ec935fbd4a7db0e46959afac6b95"
      url "https://github.com/Sknoww/drift/releases/download/v#{version}/drift_#{version}_linux_arm64.tar.gz"
    end
  end

  name "drift"
  desc "Ticket-based git TUI"
  homepage "https://github.com/Sknoww/drift"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "drift"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/drift"]
    end
  end

  # No zap stanza required

end
