# This file was generated by GoReleaser. DO NOT EDIT.
cask "drift" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "27cca964280b0e8f5455b2ffb40db46e9b140aeafd842df4d1201c2198829f3f"
      url "https://github.com/Sknoww/drift/releases/download/v#{version}/drift_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a221657c73999cd9d52a65edfd16cb769d98132c124435c2ab072ab86d1dda22"
      url "https://github.com/Sknoww/drift/releases/download/v#{version}/drift_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "af3f633663f9c3e4e10bbc04cb4b0b1630f03f75852228f37ac39bef669dc32e"
      url "https://github.com/Sknoww/drift/releases/download/v#{version}/drift_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7ea3f67066b5b122980fdcdfa64f99bc90d303839e6247241d7276f0bad93faf"
      url "https://github.com/Sknoww/drift/releases/download/v#{version}/drift_#{version}_linux_arm64.tar.gz"
    end
  end

  name "drift"
  desc "Ticket-based git TUI"
  homepage "https://github.com/Sknoww/drift"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "drift"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/drift"]
    end
  end

  # No zap stanza required

end
