# This file was generated by GoReleaser. DO NOT EDIT.
cask "floe" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "04e0f04c308abdc8956422e5d62de220473c3a04926e1335dce30ba4cf2fa0f5"
      url "https://github.com/Sknoww/floe/releases/download/v#{version}/floe_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "54598429d40d4695964235c226115c9da1711dd08c994941195bcb8921d6eeaf"
      url "https://github.com/Sknoww/floe/releases/download/v#{version}/floe_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "681ba2245dc75c07cc0afe090fb9e2b7c73b60b15377f283996210338b2ce6d4"
      url "https://github.com/Sknoww/floe/releases/download/v#{version}/floe_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "af7d894f72358d45740026e899e9a6b96e8eae61e5fb4a75ba3ab01082f77f6b"
      url "https://github.com/Sknoww/floe/releases/download/v#{version}/floe_#{version}_linux_amd64.tar.gz"
    end
  end

  name "floe"
  desc "Carry commits between git repositories that share no history"
  homepage "https://github.com/Sknoww/floe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "floe"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/floe"]
    end
  end

  # No zap stanza required
end
